name: mermaid
region: nyc
static_sites:
  - name: web
    github:
      repo: isabelshic/mermaid
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    output_dir: dist
    environment_slug: node-js
    catchall_document: index.html
    index_document: index.html
    envs:
      - key: NPM_CONFIG_PRODUCTION
        scope: BUILD_TIME
        value: "false"
